apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: dheerajlearningdocker/emartapp-webapi:V1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  selector:
    app: books
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
