apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emongo
  labels:
    app: emongo
spec:
  selector:
    matchLabels:
      app: emongo
  serviceName: "emongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: emongo
    spec:
      containers:
      - name: emongo
        image: mongo:4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
