apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emongo
  labels:
    app: emongo
spec:
  selector:
    matchLabels:
      app: emongo
  serviceName: "emongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: emongo
    spec:
      containers:
      - name: emongo
        image: mongo:4
        env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: dbconfig
                key: mongodbname
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi

---

apiVersion: v1
kind: Service
metadata:
  name: emongo
spec:
  selector:
    app: emongo
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None

