apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  labels:
    app: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: dheerajlearningdocker/emartapp-api
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: main
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
